name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'develop/**' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make .env
      run: |
        touch .env
        echo "${{ secrets.SECRET_ENV }}" > .env
  
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKER_REPO}}:latest .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKER_REPO}}:latest

    - name: Deploy to server
      uses: fifsky/ssh-action@master
      id: deploy
      with:
        command: |
          CONTAINER_ID=$(sudo docker ps -q --filter "publish=80-80")
          if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKER_REPO}}:latest
          sudo docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKER_REPO}}:latest
        host: ${{secrets.HOST}}
        user: ${{secrets.USERNAME}}
        key: ${{secrets.KEY}}

